<?php

function skivers_jammer_get_refer()
{
    if (!isset($_SESSION['org_referer'])) {
        $_SESSION['org_referer'] = $_SERVER['HTTP_REFERER'];

        $exempt = db_query("Select name from skivers_jammer")->fetchAll();

        foreach ($exempt as $e) {
            if (preg_match("/" . $e . "/", $_SESSION['org_referer'], $matches, PREG_OFFSET_CAPTURE)) {
                return false;
            }
        }
        return true;
    } else {
        return true;
    }
}